/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        rotate: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-15deg)' },
          '75%': { transform: 'rotate(15deg)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 300ms ease-in forwards',
        rotate: 'rotate 0.3s ease-in-out',
      },
      colors: {
        primary: {
          DEFAULT: '#278CCC',
          50: '#EDF7FD',
          100: '#D5EBFA',
          200: '#A7DAF9',
          300: '#7BC4F4',
          400: '#278CCC',
          500: '#0078D4',
          600: '#1F7BB3',
          700: '#196A9A',
          800: '#125880',
          900: '#0A4766',
        },
        secondary: {
          DEFAULT: '#278CCC',
          light: '#56AEE9',
          dark: '#1F7BB3',
        },
        tertiary: {
          DEFAULT: '#A7DAF9',
        },
        background: {
          DEFAULT: '#FFFFFF',
          alt: '#F8F9FA',
          dark: '#F0F2F5',
        },
        text: {
          DEFAULT: '#333333',
          secondary: '#666666',
          light: '#999999',
          inverted: '#FFFFFF',
        },
        button: {
          text: '#FFFFFF',
          primary: '#278CCC',
          secondary: '#56AEE9',
          tertiary: '#A7DAF9',
          danger: '#FF3B30',
          success: '#34C759',
        },
        status: {
          success: '#34C759',
          warning: '#FFCC00',
          danger: '#FF3B30',
          info: '#56AEE9',
        },
        border: {
          DEFAULT: '#DDDDDD',
          light: '#EEEEEE',
          dark: '#BBBBBB',
        },
        disabled: '#E5E5E5',
        'disabled-text': '#999999',
        overlay: 'rgba(0, 0, 0, 0.5)',
        shadow: 'rgba(0, 0, 0, 0.1)',
        card: {
          orange: '#FF9500',
          green: '#0DBA39',
          purple: '#AF52DE',
          blue: '#007AFF',
          cyan: '#30B0C7',
          pink: '#FF2DC3',
          'orange-disabled-20': '#FF950033',
          'orange-disabled-40': '#FF950066',
          'green-disabled-20': '#0DBA3933',
          'green-disabled-40': '#0DBA3966',
          'purple-disabled-20': '#AF52DE33',
          'purple-disabled-40': '#AF52DE66',
          'blue-disabled-20': '#007AFF33',
          'blue-disabled-40': '#007AFF66',
          'cyan-disabled-20': '#30B0C733',
          'cyan-disabled-40': '#30B0C766',
          'pink-disabled-20': '#FF2DC333',
          'pink-disabled-40': '#FF2DC366',
        },
        social: {
          kakao: '#FEE500',
          'kakao-text': '#000000',
          google: '#FFFFFF',
          'google-text': '#333333',
        },
      },
      fontWeight: {
        thin: '100',
        light: '300',
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
      },
      fontSize: {
        'custom-heading-xl': '32px',
        xs: '12px',
        sm: '14px',
        md: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '30px',
        '4xl': '36px',
      },
      lineHeight: {
        xs: '16px',
        sm: '20px',
        md: '24px',
        lg: '28px',
        xl: '32px',
        '2xl': '36px',
        '3xl': '40px',
        '4xl': '44px',
      },
      spacing: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
      },
      borderRadius: {
        none: '0px',
        xs: '2px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      borderWidth: {
        none: '0',
        thin: '1px',
        medium: '2px',
        thick: '3px',
        'x-thick': '4px',
      },
    },
  },
  plugins: [],
};
