import { vars } from '@gluestack-ui/themed';

export const config = {
  light: vars({
    // 기본 색상 설정
    '--color-primary': '#56AEE9',
    '--color-secondary': '#278CCC',
    '--color-tertiary': '#A7DAF9',
    '--color-background': '#FFFFFF',
    '--color-background-alt': '#F8F9FA',
    '--color-background-dark': '#EEEEEE',
    '--color-text': '#000000',
    '--color-text-secondary': '#666666',
    '--color-text-light': '#999999',
    '--color-text-inverted': '#FFFFFF',
    '--color-button-text': '#FFFFFF',
    '--color-button-primary': '#56AEE9',
    '--color-button-secondary': '#278CCC',
    '--color-button-tertiary': '#A7DAF9',
    '--color-button-danger': '#DC3545',
    '--color-button-success': '#68DB7D',

    // 추가 색상 설정
    '--color-success': '#68DB7D',
    '--color-warning': '#FCE642',
    '--color-danger': '#DC3545',
    '--color-info': '#17A2B8',
    '--color-border': '#718096',
    '--color-border-light': '#E2E8F0',
    '--color-border-dark': '#2D3748',
    '--color-disabled': '#A7DAF94D',
    '--color-disabled-text': '#278CCC',
    '--color-transparent': 'transparent',
    '--color-overlay': 'rgba(0, 0, 0, 0.5)',
    '--color-shadow': 'rgba(0, 0, 0, 0.1)',

    // 카드 색상
    '--color-card-orange': '#FF9500',
    '--color-card-green': '#0DBA39',
    '--color-card-purple': '#AF52DE',
    '--color-card-blue': '#007AFF',
    '--color-card-cyan': '#30B0C7',
    '--color-card-pink': '#FF2DC3',
    '--color-card-orange-disabled-20': '#FF950033',
    '--color-card-orange-disabled-40': '#FF950066',
    '--color-card-green-disabled-20': '#0DBA3933',
    '--color-card-green-disabled-40': '#0DBA3966',
    '--color-card-purple-disabled-20': '#AF52DE33',
    '--color-card-purple-disabled-40': '#AF52DE66',
    '--color-card-blue-disabled-20': '#007AFF33',
    '--color-card-blue-disabled-40': '#007AFF66',
    '--color-card-cyan-disabled-20': '#30B0C733',
    '--color-card-cyan-disabled-40': '#30B0C766',
    '--color-card-pink-disabled-20': '#FF2DC333',
    '--color-card-pink-disabled-40': '#FF2DC366',

    // 소셜 로그인 색상
    '--color-social-kakao': '#FCE642',
    '--color-social-kakao-text': '#462000',
    '--color-social-google': '#EF4040',
    '--color-social-google-text': '#FFFFFF',

    // 타이포그래피 설정
    '--font-weight-thin': '100',
    '--font-weight-light': '300',
    '--font-weight-regular': '400',
    '--font-weight-medium': '500',
    '--font-weight-semibold': '600',
    '--font-weight-bold': '700',
    '--font-weight-extrabold': '800',

    // 폰트 사이즈
    '--font-size-xs': '10',
    '--font-size-sm': '12',
    '--font-size-md': '14',
    '--font-size-lg': '16',
    '--font-size-xl': '18',
    '--font-size-2xl': '20',
    '--font-size-3xl': '24',
    '--font-size-4xl': '28',
    '--custom-font-size': '80',

    // 라인 높이
    '--line-height-xs': '16',
    '--line-height-sm': '18',
    '--line-height-md': '20',
    '--line-height-lg': '22',
    '--line-height-xl': '24',
    '--line-height-2xl': '26',
    '--line-height-3xl': '30',
    '--line-height-4xl': '34',

    // 레이아웃 설정
    '--spacing-none': '0',
    '--spacing-xs': '4',
    '--spacing-sm': '8',
    '--spacing-md': '12',
    '--spacing-lg': '16',
    '--spacing-xl': '24',
    '--spacing-2xl': '32',

    // 테두리 설정
    '--border-radius-none': '0',
    '--border-radius-xs': '2',
    '--border-radius-sm': '4',
    '--border-radius-md': '8',
    '--border-radius-lg': '12',
    '--border-radius-xl': '16',
    '--border-radius-full': '9999',

    '--border-width-none': '0',
    '--border-width-thin': '1',
    '--border-width-medium': '2',
    '--border-width-thick': '3',
    '--border-width-x-thick': '4',
  }),

  dark: vars({
    // 기본 색상 설정 (다크모드)
    '--color-primary': '#56AEE9',
    '--color-secondary': '#278CCC',
    '--color-tertiary': '#A7DAF9',
    '--color-background': '#121212',
    '--color-background-alt': '#1E1E1E',
    '--color-background-dark': '#333333',
    '--color-text': '#E0E0E0',
    '--color-text-secondary': '#AAAAAA',
    '--color-text-light': '#999999',
    '--color-text-inverted': '#000000',
    '--color-button-text': '#FFFFFF',
    '--color-button-primary': '#56AEE9',
    '--color-button-secondary': '#278CCC',
    '--color-button-tertiary': '#A7DAF9',
    '--color-button-danger': '#DC3545',
    '--color-button-success': '#68DB7D',

    // 추가 색상 설정 (다크모드)
    '--color-success': '#68DB7D',
    '--color-warning': '#FCE642',
    '--color-danger': '#DC3545',
    '--color-info': '#17A2B8',
    '--color-border': '#718096',
    '--color-border-light': '#2D3748',
    '--color-border-dark': '#E2E8F0',
    '--color-disabled': '#A7DAF94D',
    '--color-disabled-text': '#278CCC',
    '--color-transparent': 'transparent',
    '--color-overlay': 'rgba(0, 0, 0, 0.7)',
    '--color-shadow': 'rgba(0, 0, 0, 0.3)',

    // 카드 색상 (다크모드)
    '--color-card-orange': '#FF9500',
    '--color-card-green': '#0DBA39',
    '--color-card-purple': '#AF52DE',
    '--color-card-blue': '#007AFF',
    '--color-card-cyan': '#30B0C7',
    '--color-card-pink': '#FF2DC3',
    '--color-card-orange-disabled-20': '#FF950033',
    '--color-card-orange-disabled-40': '#FF950066',
    '--color-card-green-disabled-20': '#0DBA3933',
    '--color-card-green-disabled-40': '#0DBA3966',
    '--color-card-purple-disabled-20': '#AF52DE33',
    '--color-card-purple-disabled-40': '#AF52DE66',
    '--color-card-blue-disabled-20': '#007AFF33',
    '--color-card-blue-disabled-40': '#007AFF66',
    '--color-card-cyan-disabled-20': '#30B0C733',
    '--color-card-cyan-disabled-40': '#30B0C766',
    '--color-card-pink-disabled-20': '#FF2DC333',
    '--color-card-pink-disabled-40': '#FF2DC366',

    // 소셜 로그인 색상 (다크모드)
    '--color-social-kakao': '#FCE642',
    '--color-social-kakao-text': '#462000',
    '--color-social-google': '#EF4040',
    '--color-social-google-text': '#FFFFFF',

    // 타이포그래피 설정 (다크모드)
    '--font-weight-thin': '100',
    '--font-weight-light': '300',
    '--font-weight-regular': '400',
    '--font-weight-medium': '500',
    '--font-weight-semibold': '600',
    '--font-weight-bold': '700',
    '--font-weight-extrabold': '800',

    // 폰트 사이즈 (다크모드)
    '--font-size-xs': '10',
    '--font-size-sm': '12',
    '--font-size-md': '14',
    '--font-size-lg': '16',
    '--font-size-xl': '18',
    '--font-size-2xl': '20',
    '--font-size-3xl': '24',
    '--font-size-4xl': '28',
    '--custom-font-size': '80',

    // 라인 높이 (다크모드)
    '--line-height-xs': '16',
    '--line-height-sm': '18',
    '--line-height-md': '20',
    '--line-height-lg': '22',
    '--line-height-xl': '24',
    '--line-height-2xl': '26',
    '--line-height-3xl': '30',
    '--line-height-4xl': '34',

    // 레이아웃 설정 (다크모드)
    '--spacing-none': '0',
    '--spacing-xs': '4',
    '--spacing-sm': '8',
    '--spacing-md': '12',
    '--spacing-lg': '16',
    '--spacing-xl': '24',
    '--spacing-2xl': '32',

    // 테두리 설정 (다크모드)
    '--border-radius-none': '0',
    '--border-radius-xs': '2',
    '--border-radius-sm': '4',
    '--border-radius-md': '8',
    '--border-radius-lg': '12',
    '--border-radius-xl': '16',
    '--border-radius-full': '9999',

    '--border-width-none': '0',
    '--border-width-thin': '1',
    '--border-width-medium': '2',
    '--border-width-thick': '3',
    '--border-width-x-thick': '4',
  }),
};
